apiVersion: v1
kind: Service
metadata:
  name: account-backend-service
  labels:
    app: account-backend
spec:
  selector:
    app: account-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
